/*SCRIPT SQL POUR LES NIVEAUX DE JEU*/

/*DROP*/
drop table modifications;
drop table niveau;
drop table status_terrain;
drop table mur; 


CREATE TABLE status_terrain(
	sta_id number GENERATED BY default ON NULL AS IDENTITY,
	sta_terrain varchar2(25),
	constraint STATUS_TERRAIN_PK PRIMARY KEY (sta_id)
);

CREATE TABLE mur(
	mur_id number GENERATED BY default ON NULL AS IDENTITY,
	mur_etat varchar2(25),
	constraint MUR_PK PRIMARY KEY (mur_id)
);

/*CREATE TABLE*/
CREATE TABLE niveau (
	niv_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
	niv_name varchar2(25),
	niv_date timestamp default systimestamp,
	niv_id_status number,
	niv_delais_min number,
	niv_delais_max number,
	niv_ligne_x number,
	niv_ligne_y number,
	niv_joueur1_x number,
	niv_joueur1_y number,
	niv_joueur2_x number,
	niv_joueur2_y number,
	constraint NIVEAU_PK PRIMARY KEY (niv_id),
	constraint NIVEAU_STATUS_fk FOREIGN KEY (niv_id_status) REFERENCES status_terrain(sta_id)
);

CREATE TABLE modifications(
	mod_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
	mod_pos_x number,
	mod_pos_y number,
	mod_arbre number,
	mod_id_mur number,
	mod_id_niv number,
	constraint MODIF_PK PRIMARY KEY (mod_id),
	constraint MODIF_MUR_FK FOREIGN KEY (mod_id_mur) REFERENCES mur(mur_id),
	constraint MODIF_NIVEAU_FK FOREIGN KEY (mod_id_niv) REFERENCES niveau(niv_id)
);

CREATE INDEX index_nom_niv
ON niveau (niv_name); 

INSERT INTO status_terrain(sta_terrain) VALUES ('Actif');
INSERT INTO status_terrain(sta_terrain) VALUES ('Test');
INSERT INTO status_terrain(sta_terrain) VALUES ('Inactif');

INSERT INTO mur(mur_etat) VALUES ('rien');
INSERT INTO mur(mur_etat) VALUES ('mur');
INSERT INTO mur(mur_etat) VALUES ('mur mobile');
INSERT INTO mur(mur_etat) VALUES ('mur inverse');

commit;

select * from status_terrain;
select * from niveau;

INSERT INTO niveau (niv_name, niv_id_status, niv_delais_min, niv_delais_max, niv_ligne_x, niv_ligne_y, niv_joueur1_x, niv_joueur1_y, niv_joueur2_x, niv_joueur2_y) VALUES('niv1', 1, 1, 11, 6, 6, 1,1,2,2);
INSERT INTO niveau (niv_name, niv_id_status, niv_delais_min, niv_delais_max, niv_ligne_x, niv_ligne_y, niv_joueur1_x, niv_joueur1_y, niv_joueur2_x, niv_joueur2_y) VALUES('niv2', 1, 1, 11, 6, 6, 1,1,2,2);
INSERT INTO niveau (niv_name, niv_id_status, niv_delais_min, niv_delais_max, niv_ligne_x, niv_ligne_y, niv_joueur1_x, niv_joueur1_y, niv_joueur2_x, niv_joueur2_y) VALUES('niv3', 1, 1, 11, 6, 6, 1,1,2,2);





