/*SCRIPT SQL POUR LA BALANCE DE JEU*/

/*DROP*/
drop table balance_message_setting;
drop table balance_setting;
DROP TRIGGER trigger_on_insert;
DROP TRIGGER trigger_on_insert_mess;

/*CREATE TABLE*/
CREATE TABLE balance_message_setting (
	msg_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
	msg_name varchar2(25),
	msg_max NUMBER(10),
	msg_current varchar2(500),
	constraint BALANCE_MESSAGE_SETTING_PK PRIMARY KEY (msg_id)
);

CREATE TABLE balance_setting (
	bal_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
	bal_name varchar2(25),
	bal_min NUMBER(6,2),
	bal_max NUMBER(6,2),
	bal_current NUMBER(6,2),
	constraint BALANCE_SETTING_PK PRIMARY KEY (bal_id)
);

/*CREATE TRIGGER*/
CREATE OR REPLACE TRIGGER trigger_on_insert 
	BEFORE INSERT OR UPDATE 
	ON balance_setting	
	FOR EACH ROW
BEGIN    
	IF :new.bal_min IS null THEN
		:new.bal_min := :old.bal_min;
    END IF;
	IF :new.bal_max IS null THEN
		:new.bal_max := :old.bal_max;
    END IF; 
	IF :new.bal_current IS null THEN
    	:new.bal_current := :new.bal_min;  
    END IF;   
	IF :new.bal_min > :new.bal_max THEN
        :new.bal_max := :new.bal_min;
    END IF;
    IF :new.bal_current < :new.bal_min THEN
            :new.bal_current := :new.bal_min;
    END IF;
    IF :new.bal_current > :new.bal_max THEN
        :new.bal_current := :new.bal_max;
    END IF;
END;
/
CREATE OR REPLACE TRIGGER trigger_on_insert_mess 
	BEFORE INSERT OR UPDATE 
	ON balance_message_setting	
	FOR EACH ROW
BEGIN
	IF :new.msg_max IS null THEN
		:new.msg_max := length(:new.msg_current);
	ELSIF :new.msg_max = 0 THEN
		:new.msg_max := length(:new.msg_current);	
    END IF;   
    IF length(:new.msg_current) > :new.msg_max THEN
        :new.msg_current := SUBSTR(:new.msg_current, 1, :new.msg_max);
    END IF;
END;
/


INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current ) VALUES ('speed_chars',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )VALUES('speed_rotation_chars',1000.0,2000.0,1500.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current ) VALUES('points_vie_chars',100.0,2000.0,200.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current ) VALUES('time_move_blocs',0.2,2.0,0.8);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current ) VALUES('canon_speed_ball',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current ) VALUES('canon_load_time',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current ) VALUES('mitrail_speed_ball',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current ) VALUES('mitrail_load_time',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current ) VALUES('grenade_speed_init_ball',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )  VALUES('grenade_load_time',4.0,12.0,7.0);
INSERT INTO balance_setting(bal_name, bal_min, bal_max, bal_current ) VALUES('shotgun_speed_ball',4.0,12.0,7.0);
INSERT INTO balance_setting(bal_name, bal_min, bal_max, bal_current ) VALUES('shotgun_load_time',4.0,12.0,7.0);
INSERT INTO balance_setting(bal_name, bal_min, bal_max, bal_current ) VALUES('shotgun_ouverture_fusil',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )VALUES('piege_speed_ball',4.0,12.0,7.0);
INSERT INTO balance_setting(bal_name, bal_min, bal_max, bal_current ) VALUES('piege_load_time',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )VALUES('missile_speed_ball',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )VALUES('missile_load_time',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )VALUES('spring_speed_init_jump',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )VALUES('spring_load_time',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )VALUES('size_explode_ball',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )VALUES('mess_accueil_time',4.0,12.0,7.0);
INSERT INTO balance_setting (bal_name, bal_min, bal_max, bal_current )VALUES('mess_countdown_time',4.0,12.0,7.0);


INSERT INTO balance_message_setting (msg_name, msg_max, msg_current ) VALUES('mess_accueil_content',60,'Appuyer sur F1 pour l''aide');
INSERT INTO balance_message_setting (msg_name, msg_max, msg_current ) VALUES ('mess_startGame_content',50,'Tankem!');
INSERT INTO balance_message_setting (msg_name, msg_max, msg_current ) VALUES ('mess_endGame_content',70,'a gagne!');

commit;

select * from balance_setting;
select * from balance_message_setting;
