/*SCRIPT SQL POUR*/
/**
Toutes les valeurs sont atomiques. 
Les valeurs depentent entierement de la cle primaire.
tous les attributs non cles sont dependant non transitivement de la cle primaire 
**/

/*DROP*/

DROP TRIGGER trigger_on_joueur;

drop table joueur;

drop PROCEDURE Proc_InsererJoueur;
drop PROCEDURE Proc_UpdateJoueur;



CREATE TABLE joueur (
	jou_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
	jou_nom varchar2(25) NOT NULL,
	jou_motDePasse varchar2(25) NOT NULL,
	jou_phrasePersonnelle varchar2(500) DEFAULT 'Too lazy to write a message' NOT NULL,
	jou_experience number DEFAULT 0 NOT NULL,
	jou_coolPointVie number DEFAULT 0 NOT NULL,
	jou_coolPointForce number DEFAULT 0 NOT NULL,
	jou_coolPointAgilite number DEFAULT 0 NOT NULL,
	jou_coolPointDexterite number DEFAULT 0 NOT NULL,
	jou_r number DEFAULT 0 NOT NULL,
	jou_g number DEFAULT 0 NOT NULL,
	jou_b number DEFAULT 0 NOT NULL,
	constraint JOUEUR_PK PRIMARY KEY (jou_id),
	constraint joueur_unique UNIQUE (Jou_nom)

);

/*CREATE TRIGGER*/

CREATE OR REPLACE TRIGGER trigger_on_joueur
	BEFORE INSERT OR UPDATE
	ON joueur
	FOR EACH ROW
BEGIN
	IF :new.jou_phrasePersonnelle IS null THEN
		:new.jou_phrasePersonnelle := 'Too lazy to write a message';
	END IF;
	IF :new.jou_experience IS NULL THEN
		:new.jou_experience := 0;
	END IF;
	IF :new.jou_experience > 22100 THEN
		:new.jou_experience := 22100;
	END IF;
	IF :new.jou_coolPointVie IS NULL THEN
		:new.jou_coolPointVie := 0;
	END IF;
	IF :new.jou_coolPointForce IS NULL THEN
		:new.jou_coolPointForce := 0;
	END IF;
	IF :new.jou_coolPointAgilite IS NULL THEN
		:new.jou_coolPointAgilite := 0;
	END IF;
	IF :new.jou_coolPointDexterite IS NULL THEN
		:new.jou_coolPointDexterite := 0;
	END IF;
    IF :new.jou_coolPointVie > 25 THEN
		:new.jou_coolPointVie := 25;
	END IF;
	IF :new.jou_coolPointForce > 25  THEN
		:new.jou_coolPointForce := 25;
	END IF;
	IF :new.jou_coolPointAgilite > 25  THEN
		:new.jou_coolPointAgilite := 25;
	END IF;
	IF :new.jou_coolPointDexterite > 25  THEN
		:new.jou_coolPointDexterite := 25;
	END IF;
	IF :new.jou_r IS NULL OR :new.jou_r < 0 THEN
		:new.jou_r := 0;
	END IF;
	IF :new.jou_g IS NULL OR :new.jou_g < 0 THEN
		:new.jou_g := 0;
	END IF;
	IF :new.jou_b IS NULL OR :new.jou_b < 0 THEN
		:new.jou_b := 0;
	END IF;
	IF :new.jou_r > 255  THEN
		:new.jou_r := 255;
	END IF;
	IF :new.jou_g > 255  THEN
		:new.jou_g := 255;
	END IF;
	IF :new.jou_b > 255  THEN
		:new.jou_b := 255;
	END IF;
END;
/



/******************* Debut Procedures *********************************/

CREATE OR REPLACE PROCEDURE Proc_InsererJoueur(
nom in varchar2,
motDePasse in varchar2,
phrase in varchar2,
experience in number,
pointVie in number,
pointForce in number,
pointAgilite in number,
pointDexterite in number,
r in number,
g in number,
b in number	
)
IS
experience2 number;
pointVie2 number;
pointForce2 number;
pointAgilite2 number;
pointDexterite2 number;
r2 number;
g2 number;
b2 number;
BEGIN
IF experience > 22100 THEN 
    experience2 := 2222;
ELSE
    experience2 := experience;
END IF;
IF pointVie > 25 THEN
    pointVie2 := 25;
ELSE
    pointVie2 := pointVie;
END IF;
IF pointForce > 25 THEN
    pointForce2 := 25;
ELSE
    pointForce2 := pointForce;
END IF;
IF pointAgilite > 25 THEN
    pointAgilite2 := 25;
ELSE
    pointAgilite2 := pointAgilite;
END IF;
IF pointDexterite > 25 THEN
    pointDexterite2 := 25;
ELSE
    pointDexterite2 := pointDexterite;
END IF;
IF r > 255 THEN
    r2 := 255;
ELSE
    r2 := r;
END IF;
IF g > 255 THEN
    g2 := 255;
ELSE
    g2 := g;
END IF;
IF b > 255 THEN
    b2 := 255;
ELSE
    b2 := b;
END IF;
INSERT INTO joueur(jou_nom,jou_motDePasse,jou_phrasePersonnelle,jou_experience,jou_coolPointVie,jou_coolPointForce,jou_coolPointAgilite,jou_coolPointDexterite,jou_r,jou_g,jou_b) VALUES(nom,motDePasse,phrase,experience2,pointVie2,pointForce,pointAgilite,pointDexterite,r2,g2,b2);
END;
/   







CREATE OR REPLACE PROCEDURE Proc_UpdateJoueur(
experience in NUMBER,
pointVie in NUMBER,
pointForce in NUMBER,
pointAgilite in NUMBER,
pointDex in NUMBER,
idJoueur in NUMBER
)
IS
experience2 NUMBER;
pointVie2 NUMBER;
pointForce2 NUMBER;
pointAgilite2 NUMBER;
pointDex2 NUMBER;
BEGIN
IF experience > 22100 THEN
    experience2 := 22100;
ELSE
    experience2 := experience;
END IF;
IF pointVie > 25 THEN
    pointVie2 := 25;
ELSE
    pointVie2 := pointVie;
END IF;
IF pointForce > 25 THEN
    pointForce2 := 25;
ELSE
    pointForce2 := pointForce;
END IF;
IF pointAgilite > 25 THEN
    pointAgilite2 := 25;
ELSE
    pointAgilite2 := pointAgilite;
END IF;
IF pointDex > 25 THEN
    pointDex2 := 25;
ELSE
    pointDex2 := pointDex;
END IF;
UPDATE joueur SET jou_experience =experience2, jou_coolPointVie=pointVie2, jou_coolPointForce=pointForce2, jou_coolPointAgilite=pointAgilite2, jou_coolPointDexterite=pointDex2 WHERE jou_id=idJoueur;
END;
/
commit;


