DROP TRIGGER trigger_on_coup_joueur;
DROP TRIGGER trigger_on_partie;

drop table partie;

drop table arme;
drop table coup_joueur;

drop PROCEDURE Proc_InsererCoupJoueur;
drop PROCEDURE Proc_InsererPartie;
drop PROCEDURE Proc_InsererArme;

CREATE TABLE coup_joueur (
	cou_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
	cou_totalCoup number DEFAULT 0 NOT NULL,
	cou_coupRecu number DEFAULT 0 NOT NULL,
	cou_coupAtteinCible number DEFAULT 0 NOT NULL,
	constraint COUP_JOUEUR_PK PRIMARY KEY (cou_id)
);

CREATE TABLE arme (
	arm_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
	arm_id_canon number NOT NULL,
	arm_id_mitraillette number NOT NULL,
	arm_id_grenade number NOT NULL,
	arm_id_pompe number NOT NULL,
	arm_id_piege number NOT NULL,
	arm_id_missille number NOT NULL,
	constraint ARM_PK PRIMARY KEY (arm_id),
	CONSTRAINT ARM_ID_CANON FOREIGN KEY (arm_id_canon) REFERENCES coup_joueur(cou_id) ON DELETE CASCADE,
	CONSTRAINT ARM_ID_MITRAILLETTE FOREIGN KEY (arm_id_mitraillette) REFERENCES coup_joueur(cou_id) ON DELETE CASCADE,
	CONSTRAINT ARM_ID_GRENADE FOREIGN KEY (arm_id_grenade) REFERENCES coup_joueur(cou_id) ON DELETE CASCADE,
	CONSTRAINT ARM_ID_POMPE FOREIGN KEY (arm_id_pompe) REFERENCES coup_joueur(cou_id) ON DELETE CASCADE,
	CONSTRAINT ARM_ID_PIEGE FOREIGN KEY (arm_id_piege) REFERENCES coup_joueur(cou_id) ON DELETE CASCADE,
	CONSTRAINT ARM_ID_MISSILLE FOREIGN KEY (arm_id_missille) REFERENCES coup_joueur(cou_id) ON DELETE CASCADE

);

CREATE TABLE partie (
	par_id number GENERATED BY DEFAULT ON NULL AS IDENTITY,
	par_date_debut DATE,
	par_date_fin DATE,
	par_id_joueur_gagnant number,
	par_id_joueur_perdant number,
	par_id_niveau_joue number,
	par_id_arme_gagnant number,
	par_id_arme_perdant number,
	par_distance_gagnant number,
	par_distance_perdant number,
	constraint PARTIE_PK PRIMARY KEY (par_id),
	CONSTRAINT PARTIE_ID_JOUEUR_GAGNANT FOREIGN KEY (par_id_joueur_gagnant) REFERENCES joueur(jou_id) ON DELETE CASCADE,
	CONSTRAINT PARTIE_ID_JOUEUR_PERDANT FOREIGN KEY (par_id_joueur_perdant) REFERENCES joueur(jou_id) ON DELETE CASCADE,
	CONSTRAINT PARTIE_ID_NIVEAU_JOUE FOREIGN KEY (par_id_niveau_joue) REFERENCES niveau(niv_id) ON DELETE CASCADE,
	CONSTRAINT PARTIE_ID_ARME_J1 FOREIGN KEY (par_id_arme_gagnant) REFERENCES arme(arm_id) ON DELETE CASCADE,
	CONSTRAINT PARTIE_ID_ARME_J2 FOREIGN KEY (par_id_arme_perdant) REFERENCES arme(arm_id) ON DELETE CASCADE

);

/*CREATE TRIGGER*/
CREATE OR REPLACE TRIGGER trigger_on_coup_joueur
	BEFORE INSERT OR UPDATE 
	ON coup_joueur
	FOR EACH ROW
BEGIN
	IF :new.cou_totalCoup IS null THEN
		:new.cou_totalCoup := 0;
	END IF;
	IF :new.cou_coupRecu IS null THEN
		:new.cou_coupRecu := 0;
	END IF;
	IF :new.cou_coupAtteinCible IS null THEN
		:new.cou_coupAtteinCible := 0;
	END IF;
END;
/

CREATE OR REPLACE TRIGGER trigger_on_partie
	BEFORE INSERT OR UPDATE
	ON partie
	FOR EACH ROW
BEGIN
    IF :new.par_date_debut IS null OR :new.par_date_debut > SYSDATE THEN
        :new.par_date_debut := SYSDATE;
    END IF;
	IF :new.par_distance_gagnant IS null OR :new.par_distance_gagnant < 0 THEN
		:new.par_distance_gagnant := 0;
	END IF;
	IF :new.par_distance_perdant IS null OR :new.par_distance_perdant < 0 THEN
		:new.par_distance_perdant := 0;
	END IF;
END;
/

/******************* Debut Procedures *********************************/
CREATE OR REPLACE PROCEDURE Proc_InsererCoupJoueur(
totalCoup in number,
coupRecu in number,
coupAtteinCible in number
)
IS
totalCoup2 number;
BEGIN
IF totalCoup < coupAtteinCible THEN
	totalCoup2 := coupAtteinCible;
ELSE
	totalCoup2:=totalCoup;
END IF;
INSERT INTO coup_joueur (cou_totalCoup, cou_coupRecu, cou_coupAtteinCible ) VALUES (totalCoup2,coupRecu,coupAtteinCible);
END;
/

CREATE OR REPLACE PROCEDURE Proc_InsererArme(
canon in number,
mitraillette in number,
grenade in number,
pompe in number,
piege in number,
missille in number
)
IS
BEGIN
INSERT INTO arme(arm_id_canon, arm_id_mitraillette, arm_id_grenade, arm_id_pompe, arm_id_piege, arm_id_missille) VALUES (canon, mitraillette ,grenade, pompe, piege, missille);
END;
/

CREATE OR REPLACE PROCEDURE Proc_InsererPartie(
debut in VARCHAR2,
fin in VARCHAR2,
gagnant in number,
perdant in number,
niveau in number,
armeGagnant in number,
armePerdant in number,
distanceGagnant in number,
distancePerdant in number
)
IS
BEGIN
INSERT INTO partie (par_date_debut, par_date_fin, par_id_joueur_gagnant, par_id_joueur_perdant, par_id_niveau_joue, par_id_arme_gagnant, par_id_arme_perdant, par_distance_gagnant, par_distance_perdant) VALUES (to_date(debut,'yyyy/mm/dd hh24:mi:ss'), to_date(fin,'yyyy/mm/dd hh24:mi:ss'), gagnant, perdant, niveau, armeGagnant, armePerdant, distanceGagnant, distancePerdant);
END;
/
commit;